services:

  trino:
    container_name: trino
    image: trinodb/trino:latest
    restart: always
    ports:
      - "8084:8080"
    volumes:
      - ./docker/trino/etc:/etc/trino

  graphql-trino:
    container_name: graphql-trino
    image: iromu/graphql-trino:latest
    ports:
      - "8886:8080"
    volumes:
      - ./docker/graphql-trino/etc:/etc/graphql-trino
