server.port: 8885

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

logging:
  level:
    org:
      springframework:
        data: debug
        graphql: debug

spring:
  application:
    name: graphql-trino
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /api
    rsocket:
      mapping: api
    path: /api
  cloud:
    consul:
      discovery:
        instance-group: data

graphql:
  spqr:
    gui:
      enabled: true

# NO TLS support
spring.datasource.driver-class-name: io.trino.jdbc.TrinoDriver
spring.datasource.url: jdbc:trino://localhost:8084
spring.datasource.username: trino
# Enable JDBC TLS support
# comment/change the line spring.datasource.url with:
# spring.datasource.url=jdbc:trino://<TRINO_IP>:8080?SSL=true
# spring.datasource.password=<PASSWORD>


spring.rsocket.server.mapping-path: /api
spring.rsocket.server.port: 7003
spring.rsocket.server.transport: tcp

spring.profiles.active: local

---
spring.config.activate.on-profile: docker
spring.config.import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://spring-cloud-config:8080/config}
spring.datasource.url: jdbc:trino://trino:8080
server.port: 8080
spring.rsocket.server.port: 7000
app.schemaFolder: /etc/schema
